crypto/secp256k1/secp256k1.go

**Correction to Herdius Address creation logic**
Currently as a part of herdius address creation, it performs hashing on public key using **SHA256** instead we need **SHA3-256** to be used. Now the addresses are correctly generated.
Asana Link: 
Steps to create an address
1. Hash the public key using sha3-256 function and extract the last 20 bytes of the result.
2. Add 40 to the beginning of the byte array. Length of the initial address should be 21 bytes.
3. Hash the address twice using sha256 function and take the first 4 bytes as verification code.
4. Add the verification code to the end of the initial address and get an address in base58check format through base58 encoding.
5. An encoded Herdius address begins with H will be created and is 34 bytes in length.
Sanity test and all test …

Corrected the address creation logic

---

hbi/message/plugin.go

Need to solve the intermittent issue that occurs when blockchain api service node tries to gossip with supervisor node.
Asana Link: 
Implemented with Request and Reply apis provided by Noise P2P protocol. Now connections are closing gracefully for every request served.
Sanity testing.
Sent transactions through blockchain api service to blockchain using a client.
Retrieved Block Detail
Retrieved Account Detail

Code refactoring to access blockchain services

---

appspec.yml

incorrect directory copying

---

storage/state/statedb/service.go

Block was not getting commited to db
Asana Link: 
Used internal Trie interface instead of ethtri

call statedb Trie instead of ethtrie

---

supervisor/service/service.go

call statedb instead of ethtrie

---

blockchain/service.go
blockchain/service_test.go
supervisor/service/service.go

When account state is updated for an external asset, it is replacing the existing balance.
I have also added a method to handle in case funds are to be taken out of herdius blockchain.
Asana Link: 
Balance needs to be increased rather than being replaced with a new value in tx payload
* Sanity testing to make sure existing functionalities
* make run-test
Below is the test on which an external asset is sent to block chain thrice and account is updated incrementally with every new balance.
**lingrajs-MacBook-Air:herdius lingrajmahanand$ curl http://localhost/txs/eth/H9hVMYAhKpYcFY5v1e1xFMKBtVD51EHEQM**
[{"tx_id":"HTxf327d2ea2df8bb71b16c389c1ab6390987ab1fb2","tx":{"sender_address":"H9hVMYAhKpYcFY5v1e1xFMKBtVD51EHEQM","sender_pubkey":"AvpZz1jRRiZ0AQeH+Eot40l0pF3wOKqPEmDPZarc4UVt","asset":{"cat …

External Asset Fix

---

accounts/account/service.go
accounts/account/service_test.go
supervisor/service/service.go
supervisor/service/service_test.go

Value transfer implementation logic needs to be modified for external assets according to JSON object representation of account state in herdius blockchain
Asana Link: 
[Problem description in Asana](https://app.asana.com/0/998359196895599/1123326413582231)
Required to update the balances of external addresses in a new field **EBalances** in **Account** struct. Previously balances were getting updated in **Balances** field.
1. Created unit test cases against the modified and new methods.
2. Executed **make run-test** and all tests are passed.
3. Successfully registered HER addresses for two accounts.
4. Successfully added ETH address in the above two accounts respectively.
5. Sent 5 ETH tokens to account 1 **HHy1CuT3UxCGJ3BHydLEvR5ut6HRy2qUvm**
5. Sent 1 ETH each in 3 different …

Update Transaction handling module external assets

---

supervisor/service/service.go

[Asana Link](https://app.asana.com/0/998359196895599/1123505517569072)
Whoops
Undo bad validation logic

Remove flawed validation on deposit

---

cmd/herserver/main.go
config/config.toml
storage/cache/cache.go
storage/cache/type.go
storage/state/statedb/account.go
supervisor/service/service.go
supervisor/service/wire.go
syncer/account.go
syncer/eth.go
syncer/sync.go

Asana Link:  https://app.asana.com/0/1120721568345004/1120827092955093/f
1) Getting Ethereum account Balance using eth rpc (infura) 
2) Save Account in cache
3) Update statetrie with updated Account whenever Block is created, taking account detail from cache

update accounts with eth balance from mainnet

---

supervisor/service/service.go
syncer/account.go

Asana Link: https://app.asana.com/0/0/1123906215337996/f
Iterate statetrie from nil, instead of the current stateroot
Testing done on Ubuntu and MAC os

fix external account update

---

storage/cache/type.go
supervisor/service/service.go
supervisor/service/service_test.go
syncer/eth.go

Created a new branch due to merge conflicts in [eth-update-fix](https://github.com/herdius/herdius-core/pull/53).
Asana Link: 
Resolved the merged conflict issues and worked on review comments.
Same testings as they are mentioned in [eth-update-fix](https://github.com/herdius/herdius-core/pull/53).

Created new branch to solve merge conflicts for Eth update logic fix

---

cmd/herserver/main.go
go.mod
go.sum

[Asana Link](https://app.asana.com/0/998359196895599/1123744078391201)
```
╰─➤  go run cmd/herserver/main.go -supervisor=true -groupsize=3 -peers=tcp://127.0.0.1:3002 -port=3000 -env=dev -waitTime=3
2019/05/20 10:32:17 service.go:352: Block creation wait time (3s) elapsed, but no transaction to process
2019/05/20 10:32:23 service.go:352: Block creation wait time (3s) elapsed, but no transaction to process
```
The `waitTime` doesn't accurately reflect the actual time waited for block creation.
Remove extra `time.Sleep()` statement.
<details>
<summary>waitTime=8 seconds</summary>
```
╭─bittelc@Coles-MBP ~/go/src/github.com/herdius/herdius-core  ‹resolve-inconcsistent-waittime*›
╰─➤  go run cmd/herserver/main.go -supervisor=true -groupsize=3 -peers=tcp://127.0.0.1:3002 -port=3000 -env=dev …
```

Resolve waittime issue

---

config/config.toml
syncer/account.go
syncer/btc.go
syncer/btc_test.go
syncer/token.go

Asana Link: https://app.asana.com/0/1120721568345004/1124293375637129
Use blockchain info API to sync bitcoin balance 
Create an account with BTC assets and send BTC within them
herdius-blockchain-api git:(erc20) ✗ curl http://localhost/account/HLFXAmCEmtt1u8LSfTgK9j1UGr5T57a4fh
{"nonce":1,"address":"HLFXAmCEmtt1u8LSfTgK9j1UGr5T57a4fh","balance":0,"storageRoot":"E65D744C3BD06CA8349B756DADDF468DF61D843BC960C8E2C16FBA5AC7CB3B52","publicKey":"AlaSkAhTpYzfYqUWu1G7+WlsP3U6Zu/AmVbwCsRNdkfA","erc20Address":"","EBalances":{"BTC":{"Address":"38Ay1AjMHFcqbCoDRkidG4HhSYorGxHkrn","Balance":2279659,"LastBlockHeight":0,"Nonce":0}}}
➜  herdius-blockchain-api git:(erc20) ✗ curl http://localhost/account/HDkKR1mBudicd1iprNYaxeZVn5CwqqYaEC
{"nonce":2,"address":"HDkKR1mBudicd1iprNYaxeZVn5CwqqYaEC","balance":6 …

Get external BTC balance from  blockchaininfo api

---

syncer/account.go
syncer/btc.go
syncer/btc_test.go
syncer/eth.go
syncer/sync.go
syncer/token.go

Handle API calls error gracefully
Asana Link: 
https://app.asana.com/0/1120721568345004/1125052499309431
Added unit test, handled all API calls errors

Dont update account if no new value recieved from respective api calls

---

syncer/btc.go

remove fatal, return nil error

---

supervisor/service/service.go

No panic on open files

---

README.md

README is out of date
Update README

Update README from legacy info and add new deps

---

cmd/herserver/main.go
supervisor/service/service.go

Simplify ProcessTxs by reducing number of arguments, most of the
arguments are known by the Supervisor itself.
While at it, add getter/setter for some Supervisor's fields.
Asana Link: https://app.asana.com/0/998359196895599/1125023562400545
Move some fields to Supervisor struct, add getter/setter methods for those fields.
Test passed.

supervisor/service: refactor ProcessTxs

---

Makefile

Asana Link: https://app.asana.com/0/998359196895599/1126924538576158
change port param to caps
make start-validator PORT=3001 PEERS="tcp://127.0.0.1:3000" HOST="127.0.0.1"
evaluate PORT

evaluate port param in makefile

---

cmd/herserver/main.go

init syncdb only if node is supervisor

---

cmd/herserver/main.go

deduplicate db load

---

aws/restore/restore.go

That was really dumb of me. 
Fix user-specific context.

hardcoded to my name

---

deployment/kill_old_server.sh

After PR #99, it is not used anymore.
Asana Link: https://app.asana.com/0/1125705697210963/1127276530517150
Remove un-used script.
Passed.

deployment: remove kill_old_server.sh

---

Makefile
deployment/start_server.sh

Asana Link: https://app.asana.com/0/1125705697210963/1127276530517150
Do not exit deployment script if killing process failed.
Passed.

deployment: do not exit if kill old process failed

---

deployment/start_server.sh

Asana Link: https://app.asana.com/0/1125705697210963/1127276530517150

deployment: run binary directly instead of via make

---

syncer/hbtc.go

Circle CI CD is not working.
Asana Link: 
To test it made small change by adding a temporary comment.

Circle CI CD test

---

appspec.yml

removed before install hook that stops server

---

syncer/hbtc.go

Circlie CI build issue. It requires to re-run to make it success. in the first run it fails with exit code 1.
Asana Link: 
Removed a temporary comment to auto trigger it

removed the temporary comment

---

syncer/hbtc.go

Asana Link: https://app.asana.com/0/1125705697210963/1127341057117822

syncer: fix wrong parsing hbtc balance

---

syncer/hbtc.go

Asana Link: https://app.asana.com/0/1125705697210963/1127341057117822

syncer: fix wrong initialize for hbtc map

---

syncer/hbtc.go

Asana Link: https://app.asana.com/0/1125705697210963/1127341057117822

syncer: fix missing initialize statedb ebalance

---

storage/state/statedb/service.go

Asana Link: https://app.asana.com/0/1125705697210963/1130836808542441
Add lock to guard statedb operation, so read while updating happens won't return not found.
Passed.

storage/state/statedb: add lock to guard state operation

---

deployment/start_server.sh

The log/run dir permission is too wide.
- Run kill as root
- Hardening for log/run dir
Passed.

deployment: some improvements

---

hbi/message/plugin.go

For every request that is served by blockchain server, noise p2p nonce needs to be incremented. However, it is not synchronised due to which many of the requests are served but are not received by blockchain api node.
Asana Link: 
Nonce value is now incremented synchronously.
Locally executed the transactions and they worked without any issue. I didn't face the issue with getting the account detail and transaction detail.

Nonce issue

---

syncer/account.go

Asana Link: https://app.asana.com/0/1125705697210963/1131414887961703
Run sync for accounts concurrently

syncer: run account sync concurrently

---

accounts/account/service.go
supervisor/service/service.go
supervisor/service/service_test.go

Asana Link: 
https://app.asana.com/0/998359196895599/1131632190734923
Implemented the fix to update state db
Tested both redeem and lock txs and accounts are getting updated now.
Test cases are also passed

Account update fix

---

go.mod
go.sum
syncer/account.go
syncer/btctestnet.go

Btctestnet

---

supervisor/service/service.go
syncer/btctestnet.go

When HBTC tokens are minted through lock tx, they were not appearing in Account.
This PR also contains a change related to making request to blockcypher bitcoin test network where each three requests will be sent in every 15 seconds of interval.
Asana Link: 
Test cases passed. Tested locally.

HBTC should appear in Account

---

blockchain/service.go
cmd/herserver/main.go
hbi/message/plugin.go
storage/exbalance/memory_test.go
supervisor/service/service.go
supervisor/transaction/tx.go
syncer/account.go

https://goreportcard.com/report/github.com/herdius/herdius-core#misspell

all: fix mispelling

---

p2p/network/client.go

atomic.AddUint64 is using for request nonce counter, it should generate
identical request nonce for each request. However, debugging our
situation show that the request nonce can be duplicated for 2 identical
requests, causing the strange behavior when api query core, an existed
account becomes not found.
It seems to be Go bug itself, but we are not sure. So switching to a
mutex for now.
Asana Link: https://app.asana.com/0/1125705697210963/1131414887961703
Use a mutex instead of atomic.AddUint64
Passed.
Updating herdius-blockchain-api to get latest code from core.

p2p/network: use mutex instead of atomic for request nonce

---

supervisor/service/service.go
supervisor/service/service_test.go

Update HBTC if BTC is locked
Updated tests
{
"nonce": 5,
"address": "HD2N5rjL6S4x8QE86majUFwQtCvRYQmNfB",
"balance": 0,
"storageRoot": "52C774ADD9AC32A064A78056A4B27944D82CD440615BD24D37A4076E0A7B8A9A",
"publicKey": "Amz0R4Ve2nAU0u8DRgBd9cd0veTUvOxQYuvKwflIZbqY",
"erc20Address": "",
"FirstExternalAddress": {
"BTC": "mpW7BEWcy8YYriZai1DSRHNc1xKB2zLKyD",
"ETH": "0x9aA7E9819D781eFf5B239b572c4Fe8F964a899c9"
},
"ExternalNonce": 0,
"LastBlockHeight": 6011101,
"EBalances": {
"BTC": {
"mpW7BEWcy8YYriZai1DSRHNc1xKB2zLKyD": {
"Address": "mpW7BEWcy8YYriZai1DSRHNc1xKB2zLKyD",
"Balance": 3803334,
"LastBlockHeight": 1569254,
"Nonce": 4
}
},
"ETH": {
"0x9aA7E9819D781eFf5B239b572c4Fe8F964a899c9": {
"Address": "0x9aA7E9819D781eFf5B239b572c4Fe8F964a899c9",
"Balance": 1097898766000000000,
"LastBlockHeight": …

update HBTC if lock BTC happens

---

cmd/herserver/main.go
types/opcode.go

For Asana Link: https://app.asana.com/0/1125705697210963/1132020799747227

types: add opcode definitions

---

cmd/herserver/main.go

We need to redeploy herdius core using CICD tool. Added a comment for this so that the CICD could be triggered automatically. 
Asana Link:

a comment to redeploy herdius-core to staging

---

blockchain/service.go

Query using new blockheight-blockhash db first, to get O(1) behavior, if
not found, then fallback to old db with O(n).
Asana Link: https://app.asana.com/0/1125705697210963/1132230789322257
Make get block by height O(1).

blockchain: fast path for get block by height

---

blockchain/service.go

Asana Link: https://app.asana.com/0/1125705697210963/1132230789322257

blockchain: fix wrong condition get block

---

deployment/start_server.sh

Asana Link: https://app.asana.com/0/1125705697210963/1132023436522062
Use supervisord for service manager.
Passed.

deployment: use supervisor for service manager

---

appspec.yml

Asana Link: https://app.asana.com/0/1125705697210963/1132023436522062
Passed.

run deployment as root

---

supervisor/service/service.go
supervisor/service/service_test.go

Asana Link: https://app.asana.com/0/1125705697210963/1133032885625405
Passed.

supervisor/service: propagation childblock correctly

---

cmd/herserver/main.go

Validator keeps tracking first connection with core using a global
variable. When core restart, this variable is never reset, causing
validator can not reconnect to core.
To fix it, using supervisor client request nonce instead. While at it,
also refactor some logging lines.
Asana Link: https://app.asana.com/0/1125705697210963/1114615936199215
Passed.

cmd/herserver: fix validator reconnecting when core restart issue

---

syncer/btctestnet.go

Asana Link: https://app.asana.com/0/1125705697210963/1134847413571551
Passed.

syncer:/btctestnet: only get balance when have txs

---

syncer/btctestnet.go

Asana Link: https://app.asana.com/0/1125705697210963/1134887300625215
Passed.

syncer/btctestnet: guard ext balance access

---

syncer/account.go

Update HBTC syncer

---

blockchain/service.go
cmd/herserver/main.go
supervisor/service/service.go
supervisor/service/service_test.go
supervisor/transaction/tx.go
syncer/account.go

After having decoupled the validator processing specific modules, transactions were successfully getting added to child blocks and were also getting verified. Finally child blocks were also getting added to base block. But states and blocks were not getting persisted.
Account states and transactions were not accessible due to above issue.
Asana Link: 
Corrected the approach to propagate the child blocks to validators and handling of voted child blocks in supervisor.
All test cases are getting passed.
Added 3 validators and sent transactions. It has worked as expected. Child blocks and base blocks were getting persisted in the blockchain. Accounts were also getting updated.

Validator fix

---

config/config.toml
go.mod
go.sum
syncer/account.go
syncer/tezos.go

Notion Link: https://www.notion.so/herdius/Tezos-in-Syncer-55cd3ebec32e47a5ade1f85bf8b6876b
Add tezos syncer.
Passed.
Build own tezos node if necessary.

syncer: add tezos syncer

---

blockchain/service.go

Asana Link: https://app.asana.com/0/1120721568345004/1135891783239913
Child block txs has Transactions of type transaction.Tx, while base block has transaction of type protobuf.TX
For now converting transation.TX to protobuf.Tx
1) Get Txs
2) Get txs by asset and address
3) Get Txs by address

Get Txs from Child block

---

supervisor/service/service.go
supervisor/service/service_test.go

Get Tx was not treasuring status
status was missing from transition while updating TXs

fix missing status field from Tx

---

blockchain/service.go

update status in TX

---

Makefile
cmd/herserver/main.go

Removing validator when disconnect is done synchronously after a block
time. We want to it to be removed immediately when disconnection occurs,
so moving the check in separated goroutine. It is actually have a 1
second delay, it is good enough, we can increase or remove it later if
it affects.
While at it, also refactoring the code.
Asana Link: https://app.asana.com/0/1125705697210963/1136495241324181
Passed.
Change supervisor config to adapt the change of removing supervisor flag.

cmd/herserver: remove validator immediately when disconnect

---

syncer/account.go
syncer/btctestnet.go

Notion Link: https://www.notion.so/herdius/b081bd4254c14b1eb2ada917ce4ef406?v=7fec7434ea0849afa3c4db6676e9eb76&p=84146c5ca1e54759aeabecbf416331ad
Passed.

syncer: stop btctestnet syncer when rate limit reached

---

syncer/btc.go
syncer/eth.go
syncer/external.go
syncer/hbtc.go
syncer/http.go
syncer/token.go

Notion Link: https://www.notion.so/herdius/b081bd4254c14b1eb2ada917ce4ef406?v=7fec7434ea0849afa3c4db6676e9eb76&p=84146c5ca1e54759aeabecbf416331ad
Set timeout for external calls.
Passed.

syncer: set timeout for external calls

---

syncer/eth.go
syncer/token.go

syncer: add missing context

---

syncer/account.go

syncer: limit number of concurrent goroutine

---

syncer/token.go

Notion Link: https://www.notion.so/herdius/b081bd4254c14b1eb2ada917ce4ef406?v=7fec7434ea0849afa3c4db6676e9eb76&p=84146c5ca1e54759aeabecbf416331ad
Pass timeout to erc20.
Passed.

syncer: add timeout for erc20

---

config/config.toml
supervisor/service/service.go

BTC balance was incorrectly updated when redeem transaction is performed.
Asana Link: 
All test cases are passed.
Locally tested and it is updating the balances correctly.

HBTC and BTC balance fix

---

supervisor/service/service.go

Redeem balance fix
Asana Link: 
test cases passed

redeem balance update fix

---

supervisor/service/service.go
supervisor/service/service_test.go

Need to support Tezos token in herdius-core
Asana Link: 
Test cases are passed.
**Locally tested and below is the result.**
{
"nonce": 1,
"address": "HHGUwMfRbRGcpj99tWDqUYzBAukNixBTqw",
"balance": 0,
"storageRoot": "4BFB08E40766CE6117014C08A870B315850666CBD8560FD8DB0FAA435EB4207C",
"publicKey": "Ahbul29X/e/Ho5hR950WiAxlyHpsbhZSJ2ah42GbQlIP",
"erc20Address": "",
"FirstExternalAddress": {
"XTZ": "tz1WEKDqQrjP49KUBp27AKuzVC2fBv4veirm"
},
"ExternalNonce": 0,
"LastBlockHeight": 0,
"EBalances": {
**"XTZ": {
"tz1WEKDqQrjP49KUBp27AKuzVC2fBv4veirm": {
"Address": "tz1WEKDqQrjP49KUBp27AKuzVC2fBv4veirm",
"Balance": 0,
"LastBlockHeight": 0,
"Nonce": 0
}**
}
}
}

Tezos changes

---

supervisor/service/service.go

We still have over flow of uint64 happening in few places when debiting an herdius account.
Asana Link: 
Debit should only be happening when balance in the account is greater than or equal to the amount to be debited.
Tested locally.
Test cases are passed.

Overflow fix

---

syncer/btctestnet.go

Need the api key to be changed since the current api key has reached its rate limit.
Asana Link:

Changed the api key of btc testnet

---

cmd/herserver/main.go
syncer/account.go

Notion Link: https://www.notion.so/herdius/b081bd4254c14b1eb2ada917ce4ef406?v=7fec7434ea0849afa3c4db6676e9eb76&p=22aaee0cdbf44c479223bee9211d842b
Wait syncer finish its round before quit.
Passed

cmd/herserver: wait syncer finish before quit

---

.github/pull_request_template.md

.github: change asana to notion

---

config/config.toml

Notion Link: 
Test cases are passed

Tezos RPC url change

---

syncer/account.go
syncer/dai.go

Asana Link: https://app.asana.com/0/998359196895599/1135291728808642

Sync Dai account

---

config/config.toml
syncer/account.go
syncer/btc.go
syncer/ltc.go

Notion Link: https://www.notion.so/herdius/b081bd4254c14b1eb2ada917ce4ef406?v=7fec7434ea0849afa3c4db6676e9eb76&p=9a28f4ad49ec4b729da0655fb16c421e
Passed.
Add lite coin api key to supervisor.

syncer: add ltc syncer

---

syncer/external.go

Removed the previous fix.
Notion Link:

Removed the previous fix patched for syncer

---

accounts/account/service.go
checker/checker.go
supervisor/service/service.go
symbol/symbol.go

Lock and Redeem fixes for other H Tokens
Notion Link: 
Test cases are passed
Need to perform end to end testing for all the H Tokens.

Lock and Redeem fixes

---

syncer/account.go

syncer: add missing bnb syncer

---

syncer/bnb.go

syncer: fix wrong json decode fields bnb syncer

---

syncer/htoken.go

syncer: all htoken depend on ETH

---

checker/checker.go
syncer/external.go
syncer/htoken.go

performed nil check for external balances in syncer
Notion Link:

added eth rpc url for bnb and hbnb

---

syncer/btc_test.go
syncer/external.go

Notion Link: https://www.notion.so/herdius/API-node-could-not-connect-to-core-b2d71bd4a4564942b5d5233a44be60c8

syncer: guard against external balance nil

---

hbi/message/plugin.go

Notion Link: https://www.notion.so/herdius/Tx-detail-pending-status-still-persists-bf2ff1dff490480eb450b4a675ef50d4

hbi/message: use shallow copy without external address to generate tx id

---

supervisor/service/service.go

Update the tx types to **Lend** and **Borrow** for compound specific transactions. Included this change in external tx type processing.
Did not included any test case since it is same as how external tx types are getting processed.
Notion Link: 
Locally tested and test cases are passing.

Compound tx type change

---

syncer/bnb.go
syncer/btc.go
syncer/btctestnet.go
syncer/dai.go
syncer/eth.go
syncer/htoken.go
syncer/ltc.go
syncer/tezos.go

Reduced the logging to analyse log files.
Notion Link:

commented the warning logs

---

supervisor/service/service.go

The balance of H Tokens should only be debited while they are used to call **defi mint** smart contract method.
Notion Link: 
Performed testing by sending transactions to herdius system from local set up and smart contract methods are properly processed.
**Mint:** 
https://ropsten.etherscan.io/tx/0x15adfe5061acefd46bad589e0723e4d3667298cf6126261282954bb542510423
**Redeem**
https://ropsten.etherscan.io/tx/0x2e75bf325c0d5d9e0cea65892d1f04c5bdfae3ea39b9f760b3432fbbdca9bb47

Reduce logs

---

supervisor/service/service.go

As a part of Fabric and Corda integration, we need the transactions that would be sent to these chains should also be persisted in herdius chain.
Notion Link: 
It is not performing any balance calculation. It just persists the transactions that are sent to to these blockchain. Only thing that is updated in an account is the nonce value.
Tested Locally.
All test cases are passed.

Corda and Fabric integration

---

syncer/external.go

This PR doesn't have any functional change. Removed an unnecessary comment. Need to restart the supervisor node.
Notion Link:

Need to restart supervisor
