herdius/herdius-core

README.md
appspec.yml
deployment/kill_old_server.sh
deployment/start_server.sh

We need the latest version of the master branch to be deployed at all times to a stable, persistent EC2 instances with constant IP addresses or endpoints. This need is driven by the higher-level need that we need the community to participate, and reliably interact with the Herdius test chain which is still a work in progress, and a stable way for our core team to test changes we make to the codebase.
Create a CICD pipeline for the deployment of new commits to the `master` branch. This specific pipeline lives in AWS' CodeDeploy, EC2, and CodePipeline:
1. [EC2 instance](https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Instances:instanceId=i-0822c9c142ad6c905;sort=desc:launchTime) which new commits are automatically deployed
2. [CodeDeploy …

Codedeploy cicd pipeline

---

config/config.toml
hbi/message/plugin.go

1. We are transitioning the API Node to establish [persistent connections with the Supervisor](https://github.com/herdius/herdius-blockchain-api/pull/29). The current Supervisor codebase is not able to allow this type of connection. This is due to the fact that the networking layer keeps track of how many messages have been received per connection and limits this to just 1.
2. There's a typo that's preventing all localhost'd connections from responding correctly.
1. Add iterating variable to networking package which keeps track of inbound message numbers per connection. Iterate over next message.
2. Fix typo that allows localhost responses.
@lmahanand and I both tested this by using simultaneous requests to the API node, which handled it sufficiently.
<summary>local testing</summary> …

Using localhost instead of typo; messages need different messagenum

---

Makefile
storage/state/statedb/service.go

Restarting supervisor node was not getting back same account which was loaded before
Asana Link: 
Trie was not getting saved in leveldb db
1) First supervisor node  will create statedb directory and loads default accounts
start-supervisor: delete-db-dirs create_db_dirs
2) Stop supervisor node and start again without deleting statedb directory by removing  delete-db-dirs create_db_dirs
3) Account which was loaded in first run will be available 
This fix just commit trie of  default accounts data, trie.commit() is being used in many places but it is not using internal Trie Interface need to find out the occurence of commit and replave it
Need to finalize the flow at what duration trie should be commited to db, (Will be looking into geth client about this)

commit trie to underline db too

---

hbi/message/plugin.go

When client sends a TX request with an incorrect Transaction Nonce, it should reply to client that transaction nonce is incorrect. However, replies were getting hung since message nonce was not incremented.
Asana Link: 
Nonce value is incremented in the code of `hbi/message/plugin.go` file when blockchain replies to client.
**Request with the Correct Nonce**
```
9:33AM INF Tx ID : HTx2cd9d9a04bc73edd33dca1bf851c61479b054cb6
2019/04/24 09:33:41 mempool.go:74: mempool txcount after remove: 0
9:33AM INF New Block Added
9:33AM INF Block Id: DE30D0C6FD821FD9D8F88B3FA9B72C967C716FF7601A0C608168ED50FBF306E2
9:33AM INF Last Block Id: 8AB80DA5F0BE34BE807BFD5C659FCBCD1F857CB57521FF5BBC3985E333A235D4
9:33AM INF Block Height: 66
9:33AM INF Timestamp : 2019-04-24 09:07:20 +0530 IST
```
**Request with …

Due to reuse of message nonce replies were not sent back to client

---

deployment/start_server.sh

Logging on remote machines is useless, as the current logging mechanism is to `/dev/null` for both stdout and stderr. Logging is important for us to be able to view for debugging issues.
Log all server output to a file in `/var/log/herdius/herdius-blockchain-api/log/server.log` including both stdout and stderr. Delete this file upon new server start, so as to not fill disk space on API node.

Log to file and rewrite; not stdout

---

accounts/account/service.go
accounts/account/service_test.go

1. No tests for `TestAccountNonce`.
2. Only transactions with nonce one greater than the account nonce should be accepted into the memory pool.
1. Add tests.
2. `== +1` instead of `>`
Red-Green tests created and completed.

Tests and only nonce of +1 can be accepted

---

supervisor/service/service.go
supervisor/service/service_test.go

While registering multiple external address to an account, current external address entry replaces the old one in the map.
For example, below is an entry of ETH present in the **EBalances** field.
`{"Nonce":"7","Address":"H8mRDupEc8s1Zmp6rbT88pispJ1BJCB7sj","PublicKey":"AoxCritcTHTGhDCnsGyUqm9NSt98U8hlC6IlvN5oms7W","StateRoot":"","AddressHash":"","Balance":"13","EBalances":{"ETH":{"Address":"0xD8f647855876549d2623f52126CE40D053a2ef6A","Balance":"300","LastBlockHeight":"0","Nonce":"0"}}}`
If I try to add BTC entry to it, then ETH entry is removed and BTC entry is only present in **EBalances** field.
`{"Nonce":"8","Address":"H8mRDupEc8s1Zmp6rbT88pispJ1BJCB7sj","PublicKey":"AoxCritcTHTGhDCnsGyUqm9NSt98U8hlC6IlvN5oms7W","StateRoot":"","AddressHash":"","Balance":"13","EBalances":{"BTC":{"Addres …

Fix to adding multiple External asset addresses doesn't work

---

config/config.toml
syncer/account.go
syncer/eth.go

Sometime when we try to access services of ethereum networks through Infura, we get the below error.
Error getting ETH Balance from RPC 429 Too Many Requests {"jsonrpc":"2.0","error":{"code":-32005,"message":"legacy access request rate exceeded","data":{"reason":"project ID not provided","see":"https://infura.io/dashboard"
Hence, accessing api services in infura needs a project id to be used.
Need to add the Project ID to environment variable **INFURAID**.
export INFURAID=PROJECT-ID
Asana Link: 
Set the environment variable with INFURAID
make run-test executed for all the tests.
Sent transactions and they are working fine.
Sent transaction to retrieve the balance from Ethereum chain and it is correctly getting updated.

Infura project id integeration

---

aws/aws.go
deployment/start_server.sh

Self-explanatory.
The tempfile location for the S3 backups is invalid. Server unable to push due to this.
Also need a region.
Fix location so as to create tmpfile in current directory

Temp file location was invalid

---

Makefile
cmd/herserver/main.go

We're flushing the mempool way too fast on staging. We already have over 180k blocks in the chain, and most of those contain no transactions.
If we are to backup the entire chain to S3, this will be prohibitively expensive.
Slowing down the block creation period is a step forward in limiting our S3 costs. However, it will not be enough if we are to include all account data in each block.
Add account data into each `baseBlock` pushed to S3.

slow down block flush period

---

aws/aws.go
supervisor/service/service.go

Before merging this in, we need to evaluate the AWS charges that were incurred on June 4th, which is when I ran an entire chain backup for testing of this PR. The EC2 instance, at the time, was in us-east-1 while the S3 bucket is in Frankfurt.
[Asana Link](https://app.asana.com/0/998359196895599/1125294787698550)
The blockchain backup logic that attempts to backup the entire chain to S3 does so by opening out a series of goroutines, one for each unbacked block.
While the number of goroutines that a decent Linux server can have is somewhere north of a several millions, the number of open files a linux server can handle is in the tens of thousands*.
This is causing an issue because in order to write to S3, we must create temporary (open) files to upload. And because the blockchain in …

Open file limiter

---

aws/aws.go
supervisor/service/service.go

[Asana Link](https://app.asana.com/0/998359196895599/1123967465533063)
We are currently backing up all the blocks into S3 that are created by the Supervisor ("singular blocks"). However, this does not bring to fruition the need for a disaster recovery process in which the entire chain is backed up and can be restored.
This is because the statedb data is also necessary for restoring the state of the blockchain.
Backup all files in the `herdius/statedb/` directory.
* When a new block is added to the chain, both the new block is uploaded to S3, and the updated statedb files are uploaded to S3.
* When all new blocks are retroactively assessed and then uploaded to S3, only the latest block in the evaluation receives the latest updated statedb files.
The S3 directory structure is:
```
<block …
```

Add state to backup

---

cmd/herserver/main.go

After https://github.com/herdius/herdius-core/pull/72, sometimes get account details returns nothing for existed account
Add missing set state root.
Passed.

cmd/herserver: fix missing set state root

---

storage/state/statedb/account.go
syncer/account.go

Support multiple ebalances were merged, we need a way to migrate from old account struct to new one in syncer.

syncer: support migrating from old account

---

syncer/account.go

Missing set first asset address in previous PR.

syncer: add  missing first asset address

---

accounts/account/service.go
accounts/account/service_test.go
hbi/message/plugin.go
supervisor/service/service.go
syncer/eth.go

As a part of DeFi phase 1, we need a transaction that will lock external assets such as BTC, ETH etc and mint Herdius specific external assets such as hBTC, hETH etc. This transaction should be of type **lock**. This locking transaction will have Herdius Zero Address in the ReceiverAddress field **Hx00000000000000000000000000000000**.
Asana Link: 
[Modify Tx struct for DeFi - Part 1](https://app.asana.com/0/998359196895599/1127276530517142)
Right now it has implemented the below validations:
1. Sender should have enough balance in the external asset address
2. Sender should provide correct Herdius Zero Address.
3. External Address should exist.
Along with the above, right now **lock**, transactions are successfully getting processed. However, account update in state db is yet to be …

Fund Lock Tx Part -1

---

accounts/account/service.go
accounts/account/service_test.go
hbi/message/plugin.go

Limit number of addresses per asset.
Validate the limit is reached before updating account.
Passed.

accounts: limit number of addresses per asset

---

accounts/account/service.go
accounts/account/service_test.go

Normal TX for external balance needs verification for locked amount.
Asana Link: https://app.asana.com/0/1125705697210963/1127276530517143
Add verification base on current account locked balance. The current external balance must be greater than corresponding locked amount.
Passed.

accounts: verify external balance with current lock amount

---

supervisor/service/service.go

When supervisor processes pool txs, it get all txs in pool before going
to sleep. This behavior causes delay time for all pending txs which come
in to the pool at the time supervisor sleep.
Get the txs when supervisor wakes up, we will reduce the delay time of
pending txs.
Asana Link: https://app.asana.com/0/1125705697210963/1130368524675779
Passed.

supervisor/service: get pool txs when wake up

---

supervisor/service/service.go

Locked amount and redeem amount are also need to be added in signature verification. They were being processed without having them included in the signature verification part.
Asana Link: 
Included both Locked amount and redeem amount in signature verification process.
All test cases were passed.

Locked amount and Redeem amount also need to be added in Signature

---

accounts/account/service.go
supervisor/service/service_test.go

Asana Link: 
Update FirstExternalAddress in Account return struct
updated tests 
curl http://localhost/account/HQjErP6tF4eE3uMeM7aKPv1eL3eomgDZsw
{"nonce":1,"address":"HQjErP6tF4eE3uMeM7aKPv1eL3eomgDZsw","balance":0,"storageRoot":"36353690D649392595C27F09AEE917B0E43716A311D5BF4E1ACD4D1B9D1CC96B","publicKey":"Ag7MhbMgltL6VnO5VNvwcAzK98P9U6UKpIPnM7hr8k8B","erc20Address":"","FirstExternalAddress":{"ETH":"0xD8f647855876549d2623f52126CE40D053a2ef6A"},"ExternalNonce":0,"LastBlockHeight":0,"EBalances":{"ETH":{"0xD8f647855876549d2623f52126CE40D053a2ef6A":{"Address":"0xD8f647855876549d2623f52126CE40D053a2ef6A","Balance":2673600066400000000,"LastBlockHeight":5998703,"Nonce":238}}}}

Fix FirstExternalAddress, and tests

---

syncer/account.go

Asana Link: https://app.asana.com/0/1125705697210963/1131414887961703

syncer: fix wrong wait group initialization

---

accounts/account/service.go
supervisor/service/service.go
supervisor/service/service_test.go

We send a locked tx then locked balances are getting updated with tx value rather than locked amount.
Asana Link: 
Correct it to add locked amount.
Fixed the test case `TestUpdateAccountLockedBalance `
Local testing and passed test cases.

Locked amount fix

---

cmd/herserver/main.go
p2p/network/backoff/plugin_test.go
p2p/network/builder.go
p2p/network/builder_test.go
p2p/network/network.go
p2p/network/network_utils_test.go
p2p/network/plugin_test.go
validator/service/service_test.go

As we are separting out P2P connection, netork builder should take address as value instead of specific config
updated test cases

decouple builder from config

---

supervisor/service/service.go

When calculating validators slice in groupValidators, we ended up making
the validators slice contains empty string, due to:
make([]string, len(s.Validator))
It causes the slice contains len(s.Validator) empty string "". That code
still pass test, because we only care about the number of validator in
each group. So empty string appears as a valid element.
Just start the slice which cap 0 fix the issue.
make([]string, 0)
Discover the bug while doing asana Link: https://app.asana.com/0/1125705697210963/1114615936199215
Create the validators slice with cap 0.
Passed.

supervisor/service: fix wrong validators allocation

---

accounts/account/service.go
accounts/account/service_test.go
config/config.toml
supervisor/service/service.go
syncer/account.go

When redeem transaction is sent, account nonce in herdius state is not getting incremented.
Asana Link: 
All test cases passed.
Fix is not breaking existing functionalities.
Both lock and redeem functionalities are tested and worked fine.

Redeem nonce fix

---

hbi/message/plugin.go

When redeem **HBTC** transaction is sent, blockchain implementation checks whether the account has BTC that is locked and fund to be redeemed is less than or equal to locked amount. However, this check fails when HBTC is transferred off chain or not in herdius chain. We need to support the redeem functionality even if HBTC transfer takes place outside of herdius chain or eco system.
Asana Link: 
Removed the redeem balance verification call.
All test cases are passed.
Tested locally.

Removed Redeem balance verification

---

supervisor/service/service.go

While performing external transactions, balance check was handled incorrectly where in even if the account had balance, transaction was failing due to low balance.
Asana Link: 
All test cases passed.
Locally performed end to end testing.

Balance check fix

---

cmd/herserver/main.go
syncer/account.go
syncer/hbtc.go

Currently, SyncAllAccounts always uses dev config. Passing env param to
SyncAllAccounts, so it can use different config for each env.
Notion Link: https://www.notion.so/herdius/b081bd4254c14b1eb2ada917ce4ef406?v=7fec7434ea0849afa3c4db6676e9eb76&p=84146c5ca1e54759aeabecbf416331ad
Passed.

syncer: fix wrong config read in

---

supervisor/service/service.go

When redeem HBTC transaction is sent, incorrect unlocked BTC is getting credited to account.
Asana Link: 
Tested locally.
All test cases are passed

BTC balance credit fix

---

syncer/btctestnet.go
syncer/external.go

Due to datatype overflow when converting bigint uint64, balances are getting updated incorrectly through syncer.
Notion Link: 
https://www.notion.so/herdius/Balance-overflow-c2f653dda77a4a438d762ba832f18c98
Test cases are passed.

overflow issue

---

syncer/btctestnet.go

first entry in external storage is not updated, causing btctestnet stop
sync external balance.
Asana Link:

syncer: fix btctestnet not update

---

accounts/account/service.go
accounts/account/service_test.go
hbi/message/plugin.go

While redeem transaction is sent, then balance should be verified in HBTC or HTZX address instead it is verifying the BTC or TZX address.
Notion Link: 
Added to verify the tx type based on which balances will be verified.
Locally it is tested and working fine.
Test cases are also passed.

Balance verification bug during redeem

---

checker/checker.go
checker/checker_test.go
config/config.go
hbi/message/plugin.go

ETH Network status check before processing ethereum specific external assets specific assets.
Notion Link: 
[Process ETH, Lock and Redeem transaction if ETH connection is stable](https://www.notion.so/herdius/Process-ETH-Lock-and-Redeem-transaction-if-ETH-connection-is-stable-58373988ba084826ad54fdb3e2d52e50)
Test cases are passed.
Locally executed the transactions and they are working fine. Existing functionalities are not breaking.

Eth network check

---

syncer/external.go

Lock BTC tx, Redeem HBTC tx and again Lock BTC tx has resulted in incorrect HBTC balance getting updated by syncer since the last cache was still having balance of HBTC from first lock tx.
Notion Link:

Balance issue in syncer

---

blockchain/service.go
hbi/message/plugin.go

Transaction ID is created base on protobuf.Tx payload. Since when we
added ExternalAddress to protobuf.Tx payload, it's a map, so the order
of key-element is not specified. So when we marshal json it, the data
return can be different between runs.
To fix it, we can exclude ExternalAddress from tx payload.
Notion Link: https://www.notion.so/herdius/Tx-detail-pending-status-still-persists-bf2ff1dff490480eb450b4a675ef50d4
Exclude external address before marshal JSON tx.
Passed.

hbi,blockchain: fix create tx id
